
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author omerf
 */
public class KullanıcıEkleme extends javax.swing.JFrame {

    ArrayList<String> emails = new ArrayList<String>();
    ArrayList<String> passwords = new ArrayList<String>();

    /**
     * Creates new form KullanıcıEkleme
     */
    public KullanıcıEkleme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblŞifre = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnGirişYap = new javax.swing.JButton();
        lblGirişYap = new javax.swing.JLabel();
        lblKayıtol = new javax.swing.JLabel();
        btnKayıtOl = new javax.swing.JButton();
        lblWarningGiriş = new javax.swing.JLabel();
        lblWarningKayıt = new javax.swing.JLabel();
        lblSuccessLogin = new javax.swing.JLabel();
        lblNoLoginAcoount = new javax.swing.JLabel();
        fldpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email Adresini Giriniz:");

        lblŞifre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblŞifre.setText("Şifreyi Giriniz:");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInfo.setText("Giriş Sayfası");

        btnGirişYap.setBackground(new java.awt.Color(153, 153, 153));
        btnGirişYap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGirişYap.setText("Giriş Yap");
        btnGirişYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirişYapActionPerformed(evt);
            }
        });

        lblGirişYap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGirişYap.setText("Kayıtlı Bir Hesap Varsa Giriş Yapın");

        lblKayıtol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblKayıtol.setText("Kayıtlı Bir Hesap Yoksa Kayıt Yapın");

        btnKayıtOl.setBackground(new java.awt.Color(153, 153, 153));
        btnKayıtOl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKayıtOl.setText("Kayıt Ol");
        btnKayıtOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayıtOlActionPerformed(evt);
            }
        });

        lblWarningGiriş.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblWarningKayıt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblSuccessLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNoLoginAcoount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(lblŞifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGirişYap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKayıtol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGirişYap, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(txtEmail)
                    .addComponent(btnKayıtOl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fldpassword))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWarningKayıt, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(lblWarningGiriş, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(lblSuccessLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(lblNoLoginAcoount, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblŞifre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGirişYap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGirişYap, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lblWarningGiriş, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblKayıtol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKayıtOl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWarningKayıt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNoLoginAcoount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSuccessLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayıtOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayıtOlActionPerformed

        emails.add(txtEmail.getText());
        passwords.add(fldpassword.getText());
        lblSuccessLogin.setText("Successfull Login.");
        txtEmail.setText("");
        fldpassword.setText("");
        lblNoLoginAcoount.setText("");
    }//GEN-LAST:event_btnKayıtOlActionPerformed
//    emails.contains(txtEmail.getText()) && passwords.contains(txtŞifre.getText())
    private void btnGirişYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirişYapActionPerformed
        if(emails.isEmpty()){
            lblNoLoginAcoount.setText("There is no registered account.");
        }else{
            for (int i = 0; i < emails.size(); i++) {
                if (txtEmail.getText().equals(emails.get(i)) && fldpassword.getText().equals(passwords.get(i))) {
                    lblWarningGiriş.setText("Access succesfuly.");
                    lblWarningKayıt.setText("");
                    lblSuccessLogin.setText("");
                    txtEmail.setText("");
                    fldpassword.setText("");
                    lblNoLoginAcoount.setText("");
                } else {
                    lblWarningKayıt.setText("There is not an acoount like that please check password or email.");
                    lblWarningGiriş.setText("");
                    lblSuccessLogin.setText("");
                    txtEmail.setText("");
                    fldpassword.setText("");
                    lblNoLoginAcoount.setText("");
                }
            }
        }
        


    }//GEN-LAST:event_btnGirişYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıEkleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGirişYap;
    private javax.swing.JButton btnKayıtOl;
    private javax.swing.JPasswordField fldpassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGirişYap;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKayıtol;
    private javax.swing.JLabel lblNoLoginAcoount;
    private javax.swing.JLabel lblSuccessLogin;
    private javax.swing.JLabel lblWarningGiriş;
    private javax.swing.JLabel lblWarningKayıt;
    private javax.swing.JLabel lblŞifre;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
